# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180921_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=models.TextField(default='', max_length=200),
        ),
    ]
