# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_short_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idef', models.IntegerField(default=0)),
                ('type_Flat_Land', models.CharField(default='flat', max_length=200)),
                ('subtype_Rent_Sale', models.CharField(default='rent', max_length=200)),
                ('district', models.CharField(default='0', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('bank_price', models.IntegerField(default=0)),
                ('adres', models.CharField(default='', max_length=200)),
                ('room', models.IntegerField(default=0)),
                ('square', models.IntegerField(default=0)),
                ('live_square', models.IntegerField(default=0)),
                ('kitchen_square', models.IntegerField(default=0)),
                ('price_for_square', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('floors', models.IntegerField(default=0, verbose_name='этажи')),
                ('year', models.IntegerField(default=0)),
                ('house_type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='22'),
        ),
    ]
