# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180923_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='house_material',
            field=models.CharField(default='', max_length=200, verbose_name='Материал дома'),
        ),
        migrations.AddField(
            model_name='flat',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Картинка в превью. Обязательно.'),
        ),
        migrations.AddField(
            model_name='flat',
            name='seller_name',
            field=models.CharField(default='', max_length=200, verbose_name='Имя продавца'),
        ),
        migrations.AddField(
            model_name='flat',
            name='seller_phone',
            field=models.CharField(default='', max_length=200, verbose_name='Номер продавца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='adres',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='bank_price',
            field=models.IntegerField(default=0, verbose_name='Цена в ипотеку'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(default='0', max_length=200, verbose_name='Район (без ошибок, а то не сработает)'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floors',
            field=models.IntegerField(default=0, verbose_name='Колличество этажей'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house_type',
            field=models.CharField(default='', max_length=200, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='idef',
            field=models.IntegerField(default=0, verbose_name='Идентификатор (Уникальный!!!)'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='kitchen_square',
            field=models.IntegerField(default=0, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='live_square',
            field=models.IntegerField(default=0, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price_for_square',
            field=models.IntegerField(default=0, verbose_name='Цена за квадрат'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room',
            field=models.IntegerField(default=0, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square',
            field=models.IntegerField(default=0, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='subtype_Rent_Sale',
            field=models.CharField(default='rent', max_length=200, verbose_name='Продажа или аренда rent или sale'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='type_Flat_Land',
            field=models.CharField(default='flat', max_length=200, verbose_name='Участок или земля flat или land'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='identif',
            field=models.IntegerField(default=0, verbose_name='Идентификатор (Уникальный!!!)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Картинка в блоге. Обязательно.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_text',
            field=models.TextField(default='', max_length=200, verbose_name='короткий текст, в превью статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='весь текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
