# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180923_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='text',
            field=models.CharField(default=11, max_length=5200, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
